//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie_15_10_2019.Reports.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public string ExportName { get; set; }
        public Nullable<System.DateTime> ExportTime { get; set; }
        public string UserName { get; set; }
        public string LocalName { get; set; }
    }
}
